### PR TITLE
removed redundant transition declarations

### PR DESCRIPTION
**Pull request by davidpett**
`transition` property declarations should only need to be on the base element instead of the modifiers unless the `transition-duration` or `transition-timing-function`

http://codepen.io/davidpett/pen/EgbLQP

### CODE REVIEW

**Comment by davidpett** [comment]
if this looks good, i will go ahead and make the changes in the other modules as well.

**Comment by mrmrs** [comment]
Thanks for the PR but going to punt on this for now. Set this up so that the values were explicit per state and could easily be changed.

**Comment by davidpett** [comment]
That makes sense to me. My thinking was just using default tachyons it would be unnecessary, if a user wants to customize, they would be editing anyway.

No worries.

**Comment by mrmrs** [comment]
Yeah - totally get the reasoning. If you roll through the commit history I'm quite sure the module looks like the patch you proposed :) 
What I found was, by not exposing it a lot of people didn't know you could edit it / customize it. And I found the extra lines didn't add file weight for me to care about. That being said I don't have the strongest opinion on this so I'll keep it in mind for v5.

**Pull request closed without merging**
